CREATE DATABASE DEMO
USE DEMO

CREATE TABLE BENHNHAN
(
	MABN CHAR(10) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR(30) NOT NULL, 
	NGAYSINH DATETIME NOT NULL,
	GIOITINH BIT NOT NULL
)

INSERT INTO BENHNHAN VALUES
('BN1', N'ĐỖ NGỌC ĐỨC', '3/22/2021', 1),
('BN2', N'LÊ NGỌC DUY', '4/16/2022', 1),
('BN3', N'LÊ THỊ A', '5/10/2021', 0)

SELECT * FROM BENHNHAN

SELECT MABN, HOTEN, NGAYSINH, CASE GIOITINH 
WHEN 1 THEN 'NAM'
WHEN 0 THEN N'NỮ' END AS 'GIỚI TÍNH'
FROM BENHNHAN

CREATE TABLE SANPHAM
(
MASP CHAR(10) NOT NULL PRIMARY KEY,
TENSP NVARCHAR(30) NOT NULL,
SLNHAP INT NOT NULL
)


INSERT INTO SANPHAM VALUES 
('SP5', N'BÚT', 30),
('SP1', N'BÁNH', 40),
('SP4', N'KẸO', 30),
('SP2', N'BIM', 20),
('SP3', N'BÚT', 10),


SELECT * FROM SANPHAM

SELECT TENSP, SUM(SLNHAP) 
FROM SANPHAM
GROUP BY TENSP
